### ISSUE TITLE
Stop cast after use ffwd command twice

### ISSUE THREAD

**Issue by mathefeitosa** [skorokithakis/catt#250] opened 2020-03-17 16:13 UTC
The transmission is stopping after 2 uses of `catt ffwd <time>`.

**Comment by theychx** [comment] 2020-03-17 16:53
I can't reproduce this. A bit of context would be useful.

**Comment by skorokithakis** [comment] 2020-03-17 19:42
It's not "fast forward to TIME", it's "fast forward N seconds". You're fast-forwarding past the end of the video.

**Comment by theychx** [comment] 2020-03-25 20:26
I think it's safe to close this.

**Closed by theychx** 2020-03-25 20:26 UTC
