### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by j0hu** [skorokithakis/catt#384] opened 2022-01-27 08:30 UTC
Hello,

I'm on a Virtual Debian v10.11 system (VMware) and installed catt like as desripted below.

First, I installed the prequirements:

`sudo apt install python3-pip python3-setuptools`

Then I enhanced the PATH and PYTHONPATH variables:

```
echo "export PATH="$PATH:$HOME/.local/bin"" >> ~/.bashrc
echo "export PYTHONPATH="/usr/lib/python3/dist-packages:$PYTHONPATH"" >> ~/.bashrc
. ~/.bashrc
```

And last but not least I installed catt:

`pip3 install --user catt`

Until then all is well. But when I execute the catt command, I get this error:

```
~# catt
Traceback (most recent call last):
  File "/home/steve/.local/bin/catt", line 6, in <module>
    from catt.cli import main
  File "/home/steve/.local/lib/python3.7/site-packages/catt/cli.py", line 6, in <module>
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'
```

I did also a second try with the installation via pipx (before I did a VM snapshot restore), but it ends up the same error.
Also the same behavior by the installation as "root".

Further the installation of 'importlib-metadata' don't fix the error.

```
~$ pip3 install importlib-metadata
Requirement already satisfied: importlib-metadata in ./.local/lib/python3.7/site-packages (4.10.1)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in ./.local/lib/python3.7/site-packages (from importlib-metadata) (4.0.1)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.7/site-packages (from importlib-metadata) (3.7.0)
```

**==> What I have to do to get catt run ?!**

Thanks in advanced, j0hu

My installed versions:

```
~# cat /etc/debian_version
10.11
```

```
~# python3 --version
Python 3.7.3
```

```
~# pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
```

```
~$ pip3 list
Package            Version
------------------ -------------
asn1crypto         0.24.0
casttube           0.2.1
catt               0.12.6
certifi            2018.8.24
chardet            3.0.4
charset-normalizer 2.0.10
click              8.0.3
cryptography       2.6.1
entrypoints        0.3
httplib2           0.11.3
idna               2.6
ifaddr             0.1.7
importlib-metadata 4.10.1
keyring            17.1.1
keyrings.alt       3.1.1
mutagen            1.45.1
pip                18.1
protobuf           3.19.3
PyChromecast       9.2.0
pycrypto           2.6.1
pycryptodomex      3.13.0
pycurl             7.43.0.2
PyGObject          3.30.4
PySimpleSOAP       1.16.2
python-apt         1.8.4.3
python-debian      0.1.35
python-debianbts   2.8.2
pyxdg              0.25
reportbug          7.5.3-deb10u1
requests           2.27.1
SecretStorage      2.3.1
setuptools         40.8.0
six                1.12.0
typing-extensions  4.0.1
urllib3            1.24.1
websockets         10.1
wheel              0.32.3
yt-dlp             2022.1.21
zeroconf           0.31.0
zipp               3.7.0

```

**Comment by skorokithakis** [comment] 2022-01-27 08:31
Thank you for the report! This is a duplicate of #382, can you verify that the latest master fixes it for you? If so, I can release.

**Closed** 2022-01-27 08:34 UTC

**Comment by j0hu** [comment] 2022-01-27 08:50
wow, very fast response :-)

Sorry, I don't saw the other issue.

Ok, what I have to do for installing the latest master manually?

**Comment by skorokithakis** [comment] 2022-01-27 08:51
IIRC it's `pip install https://github.com/skorokithakis/catt/archive/refs/heads/master.zip`

**Comment by j0hu** [comment] 2022-01-27 08:54
hm, I get this after hitting enter:
```

~$ pip3 install https://github.com/skorokithakis/catt/archive/refs/heads/master.zip
Collecting https://github.com/skorokithakis/catt/archive/refs/heads/master.zip
  Downloading https://github.com/skorokithakis/catt/archive/refs/heads/master.zip
     | 112kB 2.8MB/s
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-ok5wfumo/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-ok5wfumo/

```

**Comment by skorokithakis** [comment] 2022-01-27 08:55
Hmm, can you download https://github.com/skorokithakis/catt/archive/refs/heads/master.zip, unzip is somewhere and `pip install .`?

**Comment by skorokithakis** [comment] 2022-01-27 09:07
Ah yeah, that's true, we use Poetry. Never mind, I guess it'll work, so I'll just release.

**Comment by j0hu** [comment] 2022-01-27 09:15
Yeah, you did my day! :-)

It works now! And the scan show me my devices! Thank you!

**Comment by skorokithakis** [comment] 2022-01-27 09:16
No problem, thanks! Did you try 0.12.7?

**Comment by j0hu** [comment] 2022-01-27 09:24
yep, version 0.12.7 fix it for me.

**Comment by skorokithakis** [comment] 2022-01-27 09:25
Excellent, thanks!
