### ISSUE TITLE
cast_site closes after 10 minutes

### ISSUE THREAD

**Issue by NeilDuToit92** [skorokithakis/catt#288] opened 2020-08-19 19:44 UTC
When casting something via the cast_site command, it automatically closes after 10 minutes.

The current workaround is to re-cast the site every 10 minutes, but it's rather annoying having to do this, not to mention it makes that annoying noise every time you cast.

I don't know if this is possible from an app perspective, but seeing as streaming apps can achieve it, it should be possible even if  it requires a bit of hacking.

**Comment by skorokithakis** [comment] 2020-08-19 19:46
Duplicate of #260.

**Closed** 2020-08-19 19:46 UTC
