### ISSUE TITLE
Error when casting local files in 0.9.2

### ISSUE THREAD

**Issue by ArtBIT** [skorokithakis/catt#174] opened 2019-03-06 14:06 UTC
When I try to cast a local file:
```
catt -d "My Chromecast" cast "$HOME/Media/test.mp4"
```

I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/catt/http_server.py", line 90, in do_GET
    copy_byte_range(mediafile, self.wfile, first, last)
  File "/usr/local/lib/python3.7/site-packages/catt/http_server.py", line 24, in copy_byte_range
    outfile.write(buf)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by theychx** [comment] 2019-03-06 14:53
Hmm, we've had these sorts of problems with local casting before, but apparently not entirely fixed. Could you provide some context, like type of media (codec etc.) and system info?

**Comment by ArtBIT** [comment] 2019-03-06 17:01
Sure.

System Info:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

Media Info:
```
$ mediainfo  "$HOME/Media/test.mp4"
General
Complete name                            : /Users/artbit/Media/test.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 1.95 GiB
Duration                                 : 1 h 42 min
Overall bit rate                         : 2 729 kb/s
Movie name                               : Test
Encoded date                             : UTC 2018-01-06 02:24:20
Tagged date                              : UTC 2018-01-06 02:24:20
Writing application                      : Lavf57.83.100
Comment                                  : Test

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1 h 42 min
Bit rate                                 : 2 500 kb/s
Width                                    : 1 920 pixels
Height                                   : 856 pixels
Display aspect ratio                     : 2.25:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (23976/1000) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.063
Stream size                              : 1.78 GiB (92%)
Writing library                          : x264 core 152 r2851M ba24899
Encoding settings                        : cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x113 / me=umh / subme=9 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-3 / threads=32 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=2pass / mbtree=1 / bitrate=2500 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=31250 / vbv_bufsize=31250 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=3:1.00
Encoded date                             : UTC 2018-01-06 02:24:20
Tagged date                              : UTC 2018-01-06 02:24:20
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 1 h 42 min
Bit rate mode                            : Constant
Bit rate                                 : 224 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 164 MiB (8%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
Encoded date                             : UTC 2018-01-06 02:24:20
Tagged date                              : UTC 2018-01-06 02:24:20
```

**Comment by ArtBIT** [comment] 2019-03-06 17:04
When I cast without specifying the device, it plays the audio on my Google Home speaker, but when I specify my chromecast device, it throws the broken pipe error.

**Comment by ArtBIT** [comment] 2019-03-07 11:28
I've tried a different file, and it seems to be working. 
```
General
Complete name                            : /Users/artbit/Media/test2.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/avc1)
File size                                : 1.45 GiB
Duration                                 : 1 h 32 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 2 250 kb/s
Encoded date                             : UTC 2012-11-20 14:22:22
Tagged date                              : UTC 2012-11-20 14:22:22

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1 h 32 min
Bit rate                                 : 2 152 kb/s
Maximum bit rate                         : 9 301 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 040 pixels
Display aspect ratio                     : 1.85:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.045
Stream size                              : 1.39 GiB (96%)
Writing library                          : x264 core 125 r2200 999b753
Encoding settings                        : cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=3 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=2152 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
Encoded date                             : UTC 2012-11-20 14:22:22
Tagged date                              : UTC 2012-11-20 14:24:35
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 1 h 32 min
Bit rate mode                            : Variable
Bit rate                                 : 96.0 kb/s
Maximum bit rate                         : 144 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 63.3 MiB (4%)
Language                                 : English
Encoded date                             : UTC 2012-11-20 14:24:31
Tagged date                              : UTC 2012-11-20 14:24:35
```


This means that the broken pipe error must be related to something specific to the file I tried in https://github.com/skorokithakis/catt/issues/174#issuecomment-470189238

**Comment by theychx** [comment] 2019-03-09 17:57
The crash is almost certainly caused by the chromecast not being able to play your media. I'm embarrassed to admit that we're currently not doing anything to avoid crashing when the chromecast does not support playback of certain local file content. Forgot about that.

@skorokithakis Any ideas?

**Comment by skorokithakis** [comment] 2019-03-09 21:15
Hmm, is a closing pipe the only thing that notifies us whether the Chromecast can play the file? That's not much to go on, but we can certainly exit with a "client disconnected, media type might not be supported" error or something similar.

**Comment by theychx** [comment] 2019-03-09 21:58
> Hmm, is a closing pipe the only thing that notifies us whether the Chromecast can play the file?

I'm afraid so.
We could look inside the header of the media file to determine if casting is possible. But that would mean new dependencies (possibly some that are not `pip`-installable). It would be useful functionality, but honestly not something I'm very keen on implementing myself.

> but we can certainly exit with a "client disconnected, media type might not be supported"

That is certainly preferable to a crash.

**Comment by skorokithakis** [comment] 2019-03-09 22:17
Even if we detect that it's not playable (and we'd have to know what each Chromecast device and software can play), there's nothing we can do other than exit with an error. We might as well display one instead of crashing and leave it at that.

It'll be a bit less certain, but the alternative isn't worth the hassle, in my opinion.

**Comment by theychx** [comment] 2019-03-10 06:24
> It'll be a bit less certain, but the alternative isn't worth the hassle, in my opinion.

I agree.

**Comment by ArtBIT** [comment] 2019-03-10 07:45
A thing to note, when I use Google Chrome browser's built-in cast feature (`... > Cast > Cast File`), the video in question casts correctly to the Chromecast. I don't know if they do any transcoding on the fly, though.

**Comment by skorokithakis** [comment] 2019-03-10 13:04
@ArtBIT Try closing the browser (or shutting down the computer) while the video is playing, if they're doing transcoding, the video will stop.

**Comment by ArtBIT** [comment] 2019-03-11 11:29
It indeed does stop when I close the browser.

**Comment by theychx** [comment] 2019-03-14 14:16
> there's nothing we can do other than exit with an error. We might as well display one instead of crashing and leave it at that

@skorokithakis It'd be cool if you could have a go at this.

**Comment by skorokithakis** [comment] 2019-03-23 23:47
@theychx Sorry, I just saw this. Will do!

**Comment by skorokithakis** [comment] 2019-03-24 00:22
I'm afraid I can't reliably reproduce this, as it doesn't always crash, but I'll push what I have.

**Comment by skorokithakis** [comment] 2019-03-24 00:24
Done. You will also have to install `gitchangelog` and `pystache`, as I've added changelog generation on commit. I think it looks pretty nifty, but let me know if you don't like something.

**Comment by theychx** [comment] 2019-03-25 13:39
@skorokithakis  I'm assuming that it's only when we squash merge that the `feat: user: Add ability to make coffee` approach is important.

Also, shouldn't `gitchangelog` and `pystache` be in `requirements_dev.txt`?

**Comment by theychx** [comment] 2019-03-25 13:56
I just made a commit and the pre-commit hook failed because of `gitchangelog`. So the extra notation should be used with any commit?

**Comment by skorokithakis** [comment] 2019-03-25 13:58
>  I'm assuming that it's only when we squash merge that the feat: user: Add ability to make coffee approach is important.

That's correct. I don't even add the `user:` part, just `new/chg/fix`.

> Also, shouldn't gitchangelog and pystache be in requirements_dev.txt?

Yes they should, I will add them now, thanks.

> I just made a commit and the pre-commit hook failed because of gitchangelog. So the extra notation should be used with any commit?

How did it fail? It shouldn't have.

**Comment by skorokithakis** [comment] 2019-03-25 14:00
That's odd, I just tried and it failed for me too. Retrying worked, hmm.

**Comment by theychx** [comment] 2019-03-25 14:02
> How did it fail? It shouldn't have.

`gitchangelog` processed your newest commit when run by the failing hook. :confused:

**Comment by skorokithakis** [comment] 2019-03-25 14:03
Hmm, what do you mean?

**Comment by theychx** [comment] 2019-03-25 14:06
The failing hook ran `gitchangelog`, which when regenerated the changelog, adding your "refuse to install on py2" stuff to it. I just tried restaging my own changes along with the new changelog, and commiting is now succesful.

**Comment by skorokithakis** [comment] 2019-03-25 14:15
My "refuse to install" stuff should have already been there, but I now realized why it fails: Whenever there's a new changelog item (from the immediately previous commit), it will fail because it added new entries, so that's normal.

**Comment by theychx** [comment] 2019-03-25 14:17
> so that's normal

Aren't we doing things in the wrong order then?

**Comment by skorokithakis** [comment] 2019-03-25 14:18
Do you want to get on Gitter to talk about this?

**Comment by theychx** [comment] 2019-03-25 14:19
yep

**Comment by theychx** [comment] 2019-03-26 13:06
@skorokithakis Any reason to keep this open?

**Comment by skorokithakis** [comment] 2019-03-26 13:07
Nope!

**Closed by skorokithakis** 2019-03-26 13:07 UTC
