### ISSUE TITLE
Cannot use IP address for device to cast

### ISSUE THREAD

**Issue by tywtyw2002** [skorokithakis/catt#330] opened 2021-03-25 17:06 UTC
Hey,

It seems like the IP address with `-d` option is broken.

```
x:~/Downloads|⇒  catt -d Bonesroom status                                                                             ⏎
Time: 00:09:28 / 00:43:07 (21%)
Remaining time: 00:33:39
State: PLAYING
Volume: 5

x:~/Downloads|⇒  catt -d 192.168.1.177 status
Error: No device found at 192.168.1.177.

x:~/Downloads|⇒  catt scan                                                                                            ⏎
Scanning Chromecasts...
192.168.1.177 - Bonesroom - Google Inc. 
```

**Comment by theychx** [comment] 2021-03-25 17:23
Can't reproduce this, I'm afraid. Try updating `catt` and/or its dependencies, if you havent already.
What kind of device are you using?

**Comment by tywtyw2002** [comment] 2021-03-25 17:34
The device is `vizio P65-C1`

Do more dig, seems the upstream pychromecast broken.  The `get_device_status` return None for device IP address.
```
In [14]: from pychromecast.dial import get_device_status, DeviceStatus

In [15]: get_device_status('192.168.1.177', None, None)

```

**Comment by tywtyw2002** [comment] 2021-03-25 17:43
device ssl problem.

```
URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1091)>
```

**Comment by skorokithakis** [comment] 2021-03-25 17:46
It sounds like it's the device that has an issue, it doesn't sound like this is catt-related.

**Comment by scooper1** [comment] 2021-03-25 18:14
reboot router then google device will normally sort out this type of 
issue
it could be ip6 issue


------ Original Message ------

**Comment by theychx** [comment] 2021-04-02 19:15
Closing as this is not an issue that we can fix here in this project.

**Closed by theychx** 2021-04-02 19:15 UTC
