### ISSUE TITLE
Question: Keep website alive

### ISSUE THREAD

**Issue by jgelon** [skorokithakis/catt#291] opened 2020-09-01 13:36 UTC
Hi all, I love using CATT to cast my Home Assistant website with camera's to my Google Home Hub. However after a few minutes the page disappears again. Is there a possibility in CATT to reload the page so the page stays on top of the screen?

**Comment by skorokithakis** [comment] 2020-09-01 13:37
Hello, this is a duplicate of #260.

**Closed by skorokithakis** 2020-09-01 13:37 UTC
