### ISSUE TITLE
Request: Use embedded subtitles

### ISSUE THREAD

**Issue by jmanabc** [skorokithakis/catt#326] opened 2021-03-05 03:30 UTC
Currently only separate subtitle files are supported, requiring manual extraction of embedded subtitles. This can be achieved with ffmpeg, but catt should either add direct support for embedded subs or work with ffmpeg automatically.

**Comment by theychx** [comment] 2021-03-09 21:27
duplicate of #117

**Closed by theychx** 2021-03-09 21:27 UTC
Labels: duplicate
